spring:
  datasource:
    url: jdbc:postgresql://localhost:1/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
scheduler:
  daily_limit_reset: 0 0 0 * * ?