CREATE TABLE user_limits (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE,
    daily_limit  NUMERIC(15, 2) NOT NULL DEFAULT 10000.00,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
